# Generated by Django 3.2.5 on 2021-07-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210724_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homepage_confirmation',
        ),
    ]
