# Generated by Django 3.2.5 on 2021-08-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0003_delete_homepage_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionnaire_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('twitter_account', models.CharField(max_length=30)),
            ],
        ),
    ]
