# Generated by Django 3.2.5 on 2021-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_questionnaire_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('twitter_account', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionnaire_response',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='questionnaire_response',
            name='twitter_account',
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='price_bus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='price_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='question_answer',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Car', 'Car')], default='Nul', max_length=3),
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='time_bus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='time_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='time_wait_bus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire_response',
            name='time_walk_to_station',
            field=models.IntegerField(default=0),
        ),
    ]
